[my_model]
git-tree-sha1 = "bfd92bafbee8184959d3538a59ad79b2d24e602c"

    [[my_model.download]]
    sha256 = "267f68264299c5e48f4b100ba159fbf6e9749f2ed83b198c1bc99891d498528c"
    url = "https://github.com/jmarsh96/NeuralMSE.jl/archive/refs/tags/models.tar.gz"

[neuralmse_models_v2]
git-tree-sha1 = "0000000000000000000000000000000000000000"
lazy = true

    [[neuralmse_models_v2.download]]
    sha256 = "0000000000000000000000000000000000000000000000000000000000000000"
    url = "https://github.com/jmarsh96/NeuralMSE.jl/releases/download/v2.0.0/models.tar.gz"
