name = "NeuralMSE"
uuid = "18905730-52b4-40ea-b814-eafe089979c2"
version = "1.1"
authors = ["Joseph Marsh"]

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
NeuralEstimators = "38f6df31-6b4a-4144-b2af-7ace2da57606"

[compat]
BSON = "0.3.9"
NeuralEstimators = "0.1.4"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
