name = "NeuralMSE"
uuid = "18905730-52b4-40ea-b814-eafe089979c2"
version = "2.0.0"
authors = ["Joseph Marsh"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
NeuralEstimators = "38f6df31-6b4a-4144-b2af-7ace2da57606"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Combinatorics = "1"
DataFrames = "1"
Distributions = "0.25"
Flux = "0.14, 0.15, 0.16"
Folds = "0.2"
JLD2 = "0.4, 0.5"
LazyArtifacts = "1.11.0"
NeuralEstimators = "0.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
